"""unique: prevent duplicate subtopic sets per run

Revision ID: 52533e1e5b14
Revises: 0d479b277f53
Create Date: 2025-09-09 18:39:55.388338

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "52533e1e5b14"
down_revision: Union[str, Sequence[str], None] = "0d479b277f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_set_multi_topic_subtopic",
        "flashcard_sets",
        ["multi_result_id", "topic_name", "subtopic_name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_set_multi_topic_subtopic", "flashcard_sets", type_="unique")
    # ### end Alembic commands ###
