"""streamline flashcards schema

Revision ID: b5d23ace9aec
Revises: 572a1d1ba891
Create Date: 2025-09-09 18:30:43.787737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5d23ace9aec"
down_revision: Union[str, Sequence[str], None] = "572a1d1ba891"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flashcard_sets",
        "tags",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.create_index(
        op.f("ix_flashcard_sets_created_at"),
        "flashcard_sets",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flashcards_created_at"), "flashcards", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_flashcards_flashcard_set_id"),
        "flashcards",
        ["flashcard_set_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_flashcard_set_order", "flashcards", ["flashcard_set_id", "order_index"]
    )
    op.create_index(
        op.f("ix_multi_flashcards_results_completed_at"),
        "multi_flashcards_results",
        ["completed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_multi_flashcards_results_created_at"),
        "multi_flashcards_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subtopic_flashcard_sets_created_at"),
        "subtopic_flashcard_sets",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subtopic_flashcard_sets_flashcard_set_id"),
        "subtopic_flashcard_sets",
        ["flashcard_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subtopic_flashcard_sets_multi_result_id"),
        "subtopic_flashcard_sets",
        ["multi_result_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_multi_topic_subtopic",
        "subtopic_flashcard_sets",
        ["multi_result_id", "topic_name", "subtopic_name"],
    )
    op.create_index(
        op.f("ix_topic_outlines_created_at"),
        "topic_outlines",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_outlines_created_at"), table_name="topic_outlines")
    op.drop_constraint(
        "uq_multi_topic_subtopic", "subtopic_flashcard_sets", type_="unique"
    )
    op.drop_index(
        op.f("ix_subtopic_flashcard_sets_multi_result_id"),
        table_name="subtopic_flashcard_sets",
    )
    op.drop_index(
        op.f("ix_subtopic_flashcard_sets_flashcard_set_id"),
        table_name="subtopic_flashcard_sets",
    )
    op.drop_index(
        op.f("ix_subtopic_flashcard_sets_created_at"),
        table_name="subtopic_flashcard_sets",
    )
    op.drop_index(
        op.f("ix_multi_flashcards_results_created_at"),
        table_name="multi_flashcards_results",
    )
    op.drop_index(
        op.f("ix_multi_flashcards_results_completed_at"),
        table_name="multi_flashcards_results",
    )
    op.drop_constraint("uq_flashcard_set_order", "flashcards", type_="unique")
    op.drop_index(op.f("ix_flashcards_flashcard_set_id"), table_name="flashcards")
    op.drop_index(op.f("ix_flashcards_created_at"), table_name="flashcards")
    op.drop_index(op.f("ix_flashcard_sets_created_at"), table_name="flashcard_sets")
    op.alter_column(
        "flashcard_sets",
        "tags",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
